;;;
;;; Registers for DMA
;;;

DMA_CTRL = $DF00
DMA_CTRL_START = $80
DMA_CTRL_INT_EN = $08
DMA_CTRL_FILL = $04
DMA_CTRL_2D = $02
DMA_CTRL_ENABLE = $01

DMA_STATUS = $DF01
DMA_STAT_BUSY = $80

DMA_FILL_VAL = $DF01
DMA_SRC_ADDR = $DF04
DMA_DST_ADDR = $DF08
DMA_COUNT = $DF0C
DMA_WIDTH = $DF0C
DMA_HEIGHT = $DF0E
DMA_STRIDE_X = $DF10
DMA_STRIDE_Y = $DF12
